// <auto-generated />
using CarShop.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShop.Data.Migrations
{
    [DbContext(typeof(CarShopDbContext))]
    partial class CarShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShop.Data.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            HorsePower = 203,
                            Model = "Camry",
                            Price = 25000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            HorsePower = 192,
                            Model = "Accord",
                            Price = 27000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Chevrolet",
                            HorsePower = 160,
                            Model = "Malibu",
                            Price = 28000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Ford",
                            HorsePower = 175,
                            Model = "Fusion",
                            Price = 26000m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Hyundai",
                            HorsePower = 191,
                            Model = "Sonata",
                            Price = 24500m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Kia",
                            HorsePower = 185,
                            Model = "Optima",
                            Price = 25500m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Nissan",
                            HorsePower = 188,
                            Model = "Altima",
                            Price = 27500m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Mazda",
                            HorsePower = 187,
                            Model = "Mazda6",
                            Price = 26500m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Subaru",
                            HorsePower = 182,
                            Model = "Legacy",
                            Price = 27000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Volkswagen",
                            HorsePower = 174,
                            Model = "Passat",
                            Price = 29000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            Brand = "BMW",
                            HorsePower = 255,
                            Model = "3 Series",
                            Price = 40000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Mercedes-Benz",
                            HorsePower = 255,
                            Model = "C-Class",
                            Price = 42000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Audi",
                            HorsePower = 201,
                            Model = "A4",
                            Price = 38000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Lexus",
                            HorsePower = 203,
                            Model = "ES",
                            Price = 39000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Tesla",
                            HorsePower = 283,
                            Model = "Model 3",
                            Price = 48000m,
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
